- hosts: localhost
  tasks:

  - name: Include main vars
    ansible.builtin.include_vars:
      file: ../vars.yml

  - name: Clone neovim
    ansible.builtin.git:
       repo: https://github.com/neovim/neovim.git
       dest: "{{ home }}/neovim"
       depth: 1
       version: stable
       update: false

  - name: "Install neovim deps"
    become: true
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - cmake
      - gettext
      - lua5.1
      - liblua5.1-0-dev

  - name: Neovim Make
    ansible.builtin.command: make CMAKE_BUILD_TYPE=RelWithDebInfo
    args:
      chdir: "{{ home }}/neovim"
      creates: "{{ home }}/neovim/build"
  
  - name: Neovim Install
    ansible.builtin.command: sudo make install
    become: true
    args:
      chdir: "{{ home }}/neovim"
