- hosts: localhost
  tasks:
    - name: Include main vars
      ansible.builtin.include_vars:
        file: ../vars.yml

    - name: Installing go with mice
      ansible.builtin.command:
        cmd: mise use --global go
