- hosts: localhost

- name: Programs setup
  ansible.builtin.import_playbook: programs/local.yml

- name: Languages setup
  ansible.builtin.import_playbook: lang/local.yml

- name: Keyboard setup
  ansible.builtin.import_playbook: keyboard/local.yml

- name: Installing dot files
  ansible.builtin.import_playbook: dotfiles.yml

